# Site settings
title: ACM @ UCR 
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 5353cf 
  secondary: 000099 
  secondary-dark: 233140 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/acm_ucr
  - title: facebook
    url: https://facebook.com/acm.at.ucr
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/acm-ucr

# Postal address (add as many lines as necessary)
address:
  - line: Riverside CA

# Build settings
markdown: kramdown
permalink: pretty
